# Generated by Django 4.2.4 on 2023-08-10 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaddar_no', models.CharField(blank=True, default=0, max_length=12)),
                ('pan_no', models.CharField(blank=True, default=0, max_length=10)),
                ('type_of_employment', models.CharField(blank=True, choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed')], default=0, max_length=250)),
                ('business_title', models.CharField(blank=True, default=0, max_length=250)),
                ('business_type', models.CharField(blank=True, choices=[('Service', 'Service'), ('Manufacturing', 'Manufacturing'), ('Treders', 'Trederd'), ('Other', 'Other')], default=0, max_length=250)),
                ('business_address', models.TextField(blank=True, default=0)),
                ('gst_registration_no', models.CharField(blank=True, default=0, max_length=50)),
                ('business_license_no', models.CharField(blank=True, default=0, max_length=50)),
                ('expected_average_annual_turnover', models.CharField(blank=True, default=0, max_length=250)),
                ('years_in_current_business', models.IntegerField(blank=True, default=0)),
                ('collateral', models.CharField(blank=True, default=0, max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Apporve', 'Apporve'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='', max_length=250)),
                ('application_timestamp', models.DateTimeField(blank=True)),
                ('remark', models.CharField(blank=True, default=0, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_with_customer', models.CharField(blank=True, default=0, max_length=250)),
                ('name', models.CharField(blank=True, default=0, max_length=150)),
                ('dob', models.DateField(blank=True, default='2000-12-12')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default=0, max_length=50)),
                ('email', models.EmailField(blank=True, default=0, max_length=254)),
                ('address', models.TextField(blank=True, default=0, max_length=250)),
                ('city', models.CharField(blank=True, default=0, max_length=50)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry')], default=0, max_length=100)),
                ('country', models.CharField(blank=True, default=0, max_length=100)),
                ('pin_code', models.IntegerField(blank=True, default=0)),
                ('mobile', models.CharField(blank=True, default=0, max_length=10)),
                ('photo', models.ImageField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('profession', models.CharField(blank=True, default=0, max_length=250)),
                ('income_certificate', models.FileField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('bank_name', models.CharField(blank=True, default=0, max_length=250)),
                ('current_account_no', models.CharField(blank=True, default=0, max_length=20)),
                ('passbook_copy', models.FileField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('ifsc_code', models.CharField(blank=True, default=0, max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gaurantors', to='application_generation.application')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('pan_card', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('business_address_proff_or_copy_of_rent_agreement', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('electricity_bill', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('msme_certificate', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('gst_cerificate', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('udhyog_adhar_registration', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('business_lincense', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('business_plan_or_proposal', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('three_year_itr_with_balance_sheet', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('collateral_document', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('stamp_duty', models.FileField(blank=True, default=0, upload_to='customer/document')),
                ('status', models.CharField(blank=True, choices=[('', ''), ('pending', 'pending'), ('done', 'done'), ('rejected', 'rejected')], default=0, max_length=250)),
                ('response_timestamp', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, choices=[('', ''), ('pending', 'pending'), ('done', 'done'), ('rejected', 'rejected')], default=0, max_length=250)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='application_generation.application')),
            ],
        ),
    ]
