# Generated by Django 4.2.4 on 2023-08-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='business_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Service', 'Service'), ('Manufacturing', 'Manufacturing'), ('Treders', 'Trederd'), ('Other', 'Other')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('', ''), ('Pending', 'Pending'), ('Apporve', 'Apporve'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='application',
            name='type_of_employment',
            field=models.CharField(blank=True, choices=[('', ''), ('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed')], default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='document',
            name='remark',
            field=models.CharField(blank=True, default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default=0, max_length=50),
        ),
    ]
