# Generated by Django 4.2.4 on 2023-08-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0002_alter_application_business_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='chetan',
        ),
    ]
