# Generated by Django 4.2.4 on 2023-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0003_rename_user_application_chetan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_timestamp',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
