# Generated by Django 4.2.4 on 2023-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0005_alter_application_application_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_timestamp',
            field=models.DateTimeField(auto_created=True, blank=True, default=0),
        ),
    ]
