# Generated by Django 4.2.4 on 2023-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0006_alter_application_application_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='chetan',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='application_timestamp',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
