# Generated by Django 4.2.4 on 2023-08-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0010_alter_guarantor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='income_certificate',
            field=models.FileField(blank=True, default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='passbook_copy',
            field=models.FileField(blank=True, default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='photo',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
    ]
