# Generated by Django 4.2.4 on 2023-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0012_alter_guarantor_income_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('Pending', 'Pending'), ('Apporve', 'Apporve'), ('Rejected', 'Rejected'), ('Disbursed', 'disbursed')], default=0, max_length=250),
        ),
    ]
