# Generated by Django 4.2.4 on 2023-08-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0013_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('Pending', 'Pending'), ('Apporve', 'Apporve'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default=0, max_length=250),
        ),
    ]
