# Generated by Django 4.2.4 on 2023-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0014_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('', ''), ('Pending', 'Pending'), ('Verify', 'Verify'), ('Apporve', 'Apporve'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default='', max_length=250),
        ),
    ]
