# Generated by Django 4.2.4 on 2023-08-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_sanctioning', '0002_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('Pending', 'pending'), ('Apporve', 'Apporve'), ('Rejected', 'Rejected')], default=0, max_length=250),
        ),
    ]
