# Generated by Django 4.2.4 on 2023-08-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disburstment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('pending', 'pending'), ('rejected', 'rejected'), ('disbursed', 'disbursed')], default=0, max_length=250),
        ),
    ]
