# Generated by Django 4.2.4 on 2023-08-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disburstment', '0002_installment_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='order_payment_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
