# Generated by Django 4.2.4 on 2023-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disburstment', '0002_alter_disbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Disbursed', 'Disbursed')], default=0, max_length=250),
        ),
    ]
