# Generated by Django 4.2.4 on 2023-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='passbook_copy',
            field=models.FileField(blank=True, null=True, upload_to='customer/bank/'),
        ),
    ]
