# Generated by Django 4.2.4 on 2023-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='martial_status',
            field=models.CharField(choices=[('', ''), ('married', 'married'), ('unmarried', 'unmarried'), ('divorced', 'divorced')], default='unmarried', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', ''), ('male', 'male'), ('female', 'female'), ('transgender', 'transgender')], max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('', ''), ('cs', 'customer'), ('lr', 'loan_representative'), ('oh', 'operational_head'), ('lo', 'loan_sanctioning_officer'), ('ad', 'admin'), ('ah', 'account_head')], max_length=20),
        ),
    ]
