# Generated by Django 4.2.4 on 2023-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_family_martial_status_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='martial_status',
            field=models.CharField(choices=[('', ''), ('married', 'married'), ('unmarried', 'unmarried'), ('divorced', 'divorced')], default='', max_length=20),
        ),
    ]
