# Generated by Django 4.2.4 on 2023-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_family_martial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('', ''), ('customer', 'customer'), ('loan_representative', 'loan_representative'), ('operational_head', 'operational_head'), ('loan_s_officer', 'loan_s_officer'), ('admin', 'admin'), ('account_head', 'account_head')], max_length=20),
        ),
    ]
